import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-gray-50 text-gray-900 min-h-screen">
        <nav className="bg-white border-b p-4 max-w-xl mx-auto mt-4 rounded shadow-sm flex gap-4">
          <Link href="/" className="font-bold text-blue-600">
            Home
          </Link>
          <Link href="/bookmarks" className="text-gray-600 hover:underline">
            Bookmarks
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
